%% callback function to provide a simple dialog box where user can enter a 
%  username and password in edit fields, confirm with one button or cancel
%  with the other
%  Rob Porritt, July 2014
% Edit, RWP, 9.19.2018 - removed the keypress function which makes the
% password disappear as it's typed.

function FL_addRestrictedDataParams(cbo, eventdata)

%  global config;

% Get position of box
  p = get(0,'DefaultFigurePosition');
  p = [p(1) p(2) p(3) p(4)*.5];
  mainHdls = findobj('Tag','dialogbox');
  BackColor = get(mainHdls,'Color');
  ForeColor = [.6 0 .2];
  
  callingPanelHandles = findobj('Tag','encryptedInfoPanel');
  tmp = get(callingPanelHandles,'UserData');
  userName=tmp{1};
  password=tmp{2};
  
  % Draw box
  restrictedParamsHandles = figure('Name','Restricted Params','Units','Pixels','Position',p,'Resize','off');
  encryptedPanel = uipanel('Tag','restrictedParamsPanel_sub','Units','Pixels','Position',[5 5 p(3)*.99 p(4)*.95],...
    'Parent',restrictedParamsHandles,'BorderType','etchedin','BackgroundColor',BackColor,'Visible','on',...
    'Title','Encrypted Access:');

%    % two edit boxes and text boxes
   textHandles1 =  uicontrol('Parent',encryptedPanel,'Units','pixel',...
     'Style','Text','FontSize',12,...
     'Position',[15 p(4)*.7 p(3)*.3 20],...
     'String', 'Enter your username:',...
     'BackgroundColor',BackColor,...
     'ForegroundColor',ForeColor);   
   editHandles1 = uicontrol('Parent',encryptedPanel,'Units','pixel',...
     'Style','Edit','FontSize',12,'Tag','userNameEntryEdit',...
     'BackgroundColor',BackColor,...
     'Position',[p(3)*.32 p(4)*.7 p(3)*.50 20],...
     'String', userName,...
     'FontName','FixedWidth','ToolTipString','Input username for restricted data access',...
     'Callback','userName=get(gcbo,''String'');');
    
textHandles2 =  uicontrol('Parent',encryptedPanel,'Units','pixel',...
    'Style','Text','FontSize',12,...
    'Position',[15 p(4)*.5 p(3)*.3 20],...
    'String', 'Enter your password:',...
    'BackgroundColor',BackColor,...
    'ForegroundColor',ForeColor);   
  editHandles2 = uicontrol('Parent',encryptedPanel,'Units','pixel',...
    'Style','Edit','FontSize',12,...
    'BackgroundColor',BackColor,...
    'Position',[p(3)*.32 p(4)*.5 p(3)*.50 20],...
    'String', '*','Tag','passwordEntryEdit',...
    'UserData', password,...
    'FontName','FixedWidth','ToolTipString','Input password for restricted data access');
 %   'Callback','tmpConfig.restrictedAccessPassword=get(gcbo,''String'');');
%  
%    % three buttons
% 
% Take the new entry
button1Handles = uicontrol('Parent',encryptedPanel,'Units','pixel',...
    'Style','pushbutton','FontSize',12,'String','Confirm',...
    'Position',[p(1)*.1  p(4)*.15 p(3)*0.2 40],...
    'BackgroundColor',BackColor,'ForegroundColor',ForeColor,...
    'Callback','tmp = cell(2,1); callingPanelHandles = findobj(''Tag'',''encryptedInfoPanel'');userNameHandles=findobj(''Tag'',''userNameEntryEdit''); tmp{1}=get(userNameHandles,''String''); tmp{2} = get(findobj(''Tag'',''passwordEntryEdit''),''userdata''); set(callingPanelHandles,''UserData'',tmp); pause(0.1); close(gcf);');

% Keep existing info
button2Handles = uicontrol('Parent',encryptedPanel,'Units','pixel',...
    'Style','pushbutton','FontSize',12,'String','Cancel',...
    'BackgroundColor',BackColor,'ForegroundColor',ForeColor,...
    'Position',[p(3)*.26+p(1)*.1 p(4)*.15 p(3)*.20 40],...
    'Callback','close(gcf);');

% Clear out (sorry this is probably really hard to read!)
button2Handles = uicontrol('Parent',encryptedPanel,'Units','pixel',...
                           'Style','pushbutton','FontSize',12,'String','Clear',...
                           'Position',[p(3)*.6+10 p(4)*.15 p(3)*.20 40],...
                           'BackgroundColor',BackColor,'ForegroundColor',ForeColor,...
                           'Callback','callingPanelHandles = findobj(''Tag'',''encryptedInfoPanel'');set(callingPanelHandles,''UserData'',{[],[]});userNameHandles=findobj(''Tag'',''userNameEntryEdit'');set(userNameHandles,''String'',[]);passwordHandles=findobj(''Tag'',''passwordEntryEdit'');set(passwordHandles,''String'',''*'',''UserData'',[])');


%set(restrictedParamsHandles,'KeyPressFcn',{@keypress_hidePassword,editHandles2});
% 
function keypress_hidePassword(hObj, data)
    pass = get(hObj,'userdata');
    switch data.Key
        case 'backspace'
        pass = pass(1:end-1);
  %
    case 'return'
        uiresume
        return
  %
    otherwise
        pass = [pass data.Character];
    end
    set(hObj,'userdata',pass)
    set(hObj,'String',char('*'*sign(pass)))

