function FuncLabPreferences = fl_default_prefs(RecordMetadataDoubles)

% 10 is stla
% 11 is stlo
latMax = max(RecordMetadataDoubles(:,10));
latMin = min(RecordMetadataDoubles(:,10));
latCenter = (latMax + latMin) / 2;
latMaxString = sprintf('%3.2f',latMax);
latMinString = sprintf('%3.2f',latMin);
latCenterString = sprintf('%3.2f',latCenter);
lonMax = max(RecordMetadataDoubles(:,11));
lonMin = min(RecordMetadataDoubles(:,11));
lonCenter = (lonMax + lonMin) / 2;
lonCenterString = sprintf('%3.2f',lonCenter);
lonMaxString = sprintf('%3.2f',lonMax);
lonMinString = sprintf('%3.2f',lonMin);


FuncLabPreferences = {...
    '10',...
    '0.01',...
    '45',...
    '0',...
    '90',...
    '0.5',...
    'P35s,P35pPs,P35sPs',...
    'AK135.vel',...
    'All',...
    'Mercator',...
    'Equidistant Azimuthal',...
    'Coastlines (low-res)',...
    latMaxString,...
    latMinString,...
    lonMinString,...
    lonMaxString,...
    latCenterString,...
    lonCenterString....
    'vel.cpt'...
    'false'...
    '1.8.2'...
    };
