PrefTitles = {...
    'Time axis increment',...
    'Ray Parameter axis increment',...
    'Backazimuth axis increment',...
    'Begin Time',...
    'End Time',...
    'Time series resample rate',...
    'Phase arrivals',...
    '1-D Velocity Model',...
    'Maps Locations',...
    'Station Map Projection',...
    'Event Map Projection',...
    'Maps Background',...
    'Station Map North Latitude',...
    'Station Map South Latitude',...
    'Station Map West Longitude',...
    'Station Map East Longitude',...
    'Event Map Center Latitude',...
    'Event Map Center Longitude',...
    'Color map',...
    'Color map reversal',...
    'Version ID',...
    };
PrefDescript = {...
    'Time axis tick mark increments (Time in seconds)',...
    'Ray parameter axis tick mark increments (Ray parameter in s/km)',...
    'Backazimuth axis tick mark increments (Backazimuth in degrees)',...
    'Time window begin time',...
    'Time window end time',...
    'New time axis dt to interpolate the old time axis to a new one with less samples',...
    'List phases to show predicted arrivals (comma delimited)',...
    'Choose a 1-D velocity model for predicted phase arrivals',...
    'Choose which stations/events to show on maps (All/Active/Inactive)',...
    'Choose a projection for the station map',...
    'Choose a projection for the event map',...
    'Choose between showing topography or filled coastlines on maps',...
    'Northern latitude for the station map',...
    'Southern latitude for the station map',...
    'West longitude for the station map',...
    'East longitude for the station map',...
    'Latitude for the center of the event map',...
    'Longitude for the center of the event map',...
    'Color map for image plots',...
    'Whether or not to flip the color map',...
    'Created with Version ID',...
    };