RecordFields = {...
    'Path: ',...
    'Station: ',...
    'Event Time: ',...
    'Edited: ',...
    'Status: ',...
    'Time Delta: ',...
    'Number of Samples: ',...
    'Begin Time: ',...
    'End Time: ',...
    'Gaussian: ',...
    'Radial RF Fit: ',...
    'Transverse RF Fit: ',...
    'Station Latitude: ',...
    'Station Longitude: ',...
    'Station Elevation: ',...
    'Event Latitude: ',...
    'Event Longitude: ',...
    'Event Depth: ',...
    'Event Magnitude: ',...
    'Event Distance: ',...
    'P-wave Slowness: ',...
    'Event Backazimuth: ',...
    };