PrefTitles = {...
    'Receiver function component',...
    '1-D Velocity Model',...
    'Phase arrivals',...
    'Y-axis increment',...
    'Gain',...
    'Records in view',...
    'Begin Time',...
    'End Time',...
    'Time series resample rate',...
    'Auto: amplitude maximum',...
    'Auto: minimum predicted fit',...
    'High pass corner (Hz)',...
    'Low pass corner (Hz)',...
    'Filter order'...
    };
PrefDescript = {...
    'Waveform component to display (Radial,Transverse)',...
    'Choose a 1-D velocity model for predicted phase arrivals',...
    'List phases to show predicted arrivals (comma delimited)',...
    'Y-axis tick mark increments (Time in seconds)',...
    'Gain of each trace',...
    'Display window size (number of traces + 1)',...
    'Time window begin time',...
    'Time window end time',...
    'New time axis delta-t to interpolate the old time axis to a new one with less samples',...
    'Auto Trace Editing: Maximum amplitude filter AFTER coherency (first) pulse on receiver functions (i.e. 70% of first pulse = 0.7)',...
    'Auto Trace Editing: Minimum fit filter of predicted receiver functions to the observations (i.e. 80% = 80)',...
    'Frequency for high pass butterworth filter (Hz). Add both high pass and low pass for bandpass. Not recommended for RFs',...
    'Frequency for low pass butterworth filter (Hz). Add both high pass and low pass for bandpass. Not recommended for RFs',...
    'Order for a filter. High order yields stepper filter sides'...
    };