RecordFields = {...
    'Path: ',...
    'Table Name: ',...
    'Bin: ',...
    'Number of Records: ',...
    'Depth Delta: ',...
    'Number of Samples: ',...
    'Begin Depth: ',...
    'End Depth: ',...
    'Gaussian: ',...
    'Backazimuth Minimum: ',...
    'Backazimuth Maximum: ',...
    'Ray Parameter Minimum: ',...
    'Ray Parameter Maximum: ',...
    'Bin Latitude: ',...
    'Bin Longitude: ',...
    'Bin Radius: ',...
    };