RecordFields = {...
    'Path: ',...
    'Station: ',...
    'Table Name: ',...
    'Number of Records: ',...
    'Time Delta: ',...
    'Number of Samples: ',...
    'Begin Time: ',...
    'End Time: ',...
    'Gaussian: ',...
    'Backazimuth Minimum: ',...
    'Backazimuth Maximum: ',...
    'Ray Parameter Minimum: ',...
    'Ray Parameter Maximum: ',...
    'Ps Weight (W1): ',...
    'PpPs Weight (W2): ',...
    'PsPs Weight (W3): ',...
    'Assumed Vp: ',...
    'Moho Depth: ',...
    'Moho Depth Error: ',...
    'Vp/Vs: ',...
    'Vp/Vs Error: ',...
    'Poisson''s Ratio: ',...
    'Poisson''s Ratio Error: '...
    };